site_name: mathtoolbox
theme: readthedocs
markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: true
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
google_analytics: ['UA-118875313-1', 'yuki-koyama.github.io']
pages:
  - 'Introduction': 'index.md'
  - 'Scattered Data Interpolation and Function Approximation':
    - 'rbf-interpolation.md'
    - 'gaussian-process-regression.md'
  - 'Dimensionality Reduction and Low-Dimensional Embedding':
    - 'classical-mds.md'
  - 'Numerical Optimization':
    - 'bfgs.md'
repo_name: GitHub
repo_url: https://github.com/yuki-koyama/mathtoolbox/
