name: build-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: packages
      run: sudo apt-get install libeigen3-dev
    - name: submodule
      run: git submodule update --init --recursive
    - name: pyenv
      run: |
        git clone https://github.com/pyenv/pyenv.git ~/.pyenv
        export PYENV_ROOT=$HOME/.pyenv
        export PATH=${PYENV_ROOT}/bin:$PATH
        eval "$(pyenv init -)"
        pyenv install -v 3.7.5
        pyenv global 3.7.5
    - name: pip
      run: pip install numpy
    - name: cmake
      run: cmake . -DMATHTOOLBOX_BUILD_EXAMPLES=ON -DMATHTOOLBOX_PYTHON_BINDINGS=ON
    - name: make
      run: make
    - name: ctest
      run: ctest -VV
