name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: packages
      run: sudo apt-get install libeigen3-dev
    - name: cmake
      run: cmake . -DMATHTOOLBOX_BUILD_EXAMPLES=ON
    - name: make
      run: make
    - name: ctest
      run: ctest
