name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: packages
      run: sudo apt-get install libeigen3-dev
    - name: submodule
      run: git submodule update --init --recursive
    - name: pyenv
      run: pyenv global 3.7 && pip install numpy
    - name: cmake
      run: cmake . -DMATHTOOLBOX_BUILD_EXAMPLES=ON -DMATHTOOLBOX_PYTHON_BINDINGS=ON
    - name: make
      run: make
    - name: ctest
      run: ctest
